---

namespace: nofusscomputing

name: git_events

version: 0.0.1

readme: README.md

authors:
  - No Fuss Computing

description: Git[ea/hub] Problem matcher parser with PR Code Review
license:
  - MIT

license_file: LICENCE

tags:
  - ci
  - event
  - rulebook
  - tools

dependencies: {}

repository: https://nofusscomputing.com/git/ansible-collections/git-events

documentation: https://nofusscomputing.com/git/ansible-collections/git-events

homepage: https://nofusscomputing.com/git/ansible-collections/git-events

issues: https://nofusscomputing.com/git/ansible-collections/git-events/issues

build_ignore: [
  '.ansible',
  artifacts/,
  '.cz.yaml',
  '.dockerignore',
  'dockerfile',
  '.git',
  'galaxy.yml',
  '*.tmp.*'

]
