---

- name: Inbound Webhook
  hosts: localhost
  match_multiple_rules: true

  sources:
    - name: Webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: "{{ GIT_EVENT_RULEBOOK_PORT | default(5000) | int }}"
        token: "{{ GIT_EVENT_RULEBOOK_TOKEN | default('-not-set-') }}"

  rules:


    - name: Trace Output
      actions:

        - debug:
            msg: "{{ event }}"
