---

- name: echo Webhook
  hosts: localhost
  match_multiple_rules: true

  sources:
    - name: Webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    # - name: Log every event
    #   condition: true
    #   action:
    #     - print_event:
    #         pretty: true

    - name: Debug print event
      condition: true
      actions:
        - debug:
            msg: "{{ event }}"

    - name: Trace print event
      condition: true
      actions:
        - print_event:
            pretty: true
